name: check_syntax

on:
  push:
    branches:
      - check_syntax

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Konfiguracja Pythona
        uses: actions/setup-python@v3
        with:
          python-version: [3.9, 3.10, 3.11]
          pip: latest

      - name: Instalacja flake8
        run: pip install flake8

      - name: Wyświetl wersję Pythona
        run: |
          python --version

